### ISSUE TITLE
Why can't modify uploadrate?

### ISSUE THREAD

**Issue by fourierr** [pyroscope-io/client#14]
- The `uploadrate` for go client can't be modified.		
https://github.com/pyroscope-io/client/blob/f925dac526a76d0611176830cc4b7bea4e6e717f/pyroscope/api.go#L64
- I propose that we should expose it to `pyroscope.Config` and align with `SampleRate`.      
- If properly, I will modify it.

**Comment by petethepig** [comment]
Implemented in v0.7.0 (#32)
