### ISSUE TITLE
EOF when uploading profiles to the server

### ISSUE THREAD

**Issue by ray2011** [pyroscope-io/client#18]
![image](https://user-images.githubusercontent.com/7893714/181871801-3cec5b93-4711-4dde-b545-f92d9c7bf2f4.png)
1.   Pyroscope server `ReadTimeout` is 10s
``` go
ctrl.httpServer = &http.Server{
		Addr:           ctrl.config.APIBindAddr,
		Handler:        handler,
		ReadTimeout:    10 * time.Second,
		WriteTimeout:   15 * time.Second,
		IdleTimeout:    30 * time.Second,
		MaxHeaderBytes: 1 << 20,
		ErrorLog:       golog.New(w, "", 0),
	}
```
In go http.Server, if one conn is established, and after `ReadTimeout`, the first req don't come, the conn would be closed.

2.  The client's updateRate is 10s, the same as `server.ReadTimeout`.  In the last update time, there can be some conn established, but dont send any request. In go http.Client, the conn is established asynchronous and then deliver request to it. Perhaps there is no request when conn is established.
3.  When client update profile, it may get a conn never send any request and establiseed 10s ago,  write to the conn successfully. At the same time, the server close the conn because 10s timeout.
4. The client would receive EOF error.

**Comment by kolesnikovae** [comment]
Hello @ray2011, thank you filing the issue!

Indeed, the traffic capture clearly says that the server closed the established connection in 10s after it was created, but `IdleTimeout` and `ReadTimeout` should have prevented this.

I think that the problem can be caused by the fact that we use the default `MaxIdleConnsPerHost` in the client settings, which limits the number of idle connections to 2 on the client site:
https://github.com/pyroscope-io/client/blob/72c28da1c0a344149dcee1264a9f3f7bc9a78ee2/upstream/remote/remote.go#L52-L86

`MaxConnsPerHost` limits the total number of connections per host, including connections in the active, and idle states.

However, it's not entirely clear for me why exactly the server initiated the connection termination (sending FIN, ACK) and not the client. It would be nice to look at the [flow graph](https://www.wireshark.org/docs/wsug_html_chunked/ChStatFlowGraph.html).

In turn, I'd suggest to try setting `MaxConnsPerHost` == `MaxIdleConnsPerHost` == `MaxIdleConns` == `number of threads (hardcoded to 4)` before digging into debugging, as this seems to be the most obvious fix.

@ray2011, what do you think?

**Comment by kolesnikovae** [comment]
Also, I'm thinking about increasing the default timeouts on the server side: with TLS transport, Go http server sets deadlines right after [accepting the connection](https://github.com/golang/go/blob/29b9a328d268d53833d2cc063d1d8b4bf6852675/src/net/http/server.go#L1867-L1872):
```go
tlsTO := c.server.tlsHandshakeTimeout()
if tlsTO > 0 {
	dl := time.Now().Add(tlsTO)
	c.rwc.SetReadDeadline(dl)
	c.rwc.SetWriteDeadline(dl)
}
```
(`tlsHandshakeTimeout` picks smallest value from `ReadTimeout`, `ReadHeaderTimeout`, and `WriteTimeout`).

While in other cases it sets the deadline [after the body is read](
https://github.com/golang/go/blob/3ba31558d1bca8ae6d2f03209b4cae55381175b3/src/net/http/server.go#L744-L756). More about it here: [So you want to expose Go on the Internet](https://blog.cloudflare.com/exposing-go-on-the-internet/#timeouts).

I would set the following settings by default:
```go
ReadTimeout: 30 * time.Second,
WriteTimeout: 30 * time.Second,
IdleTimeout: 90 * time.Second,
```

And, if TLS is configured, set all those to 90 seconds.

/cc @petethepig

**Comment by ray2011** [comment]
> Hello @ray2011, thank you filing the issue!
> 
> Indeed, the traffic capture clearly says that the server closed the established connection in 10s after it was created, but `IdleTimeout` and `ReadTimeout` should have prevented this.

The server close the established connection in 10s, the reason is `ReadTimeout`, because the connection didn't send the first request(accprding to the traffic capture), so the server read timeout, and close the connection(according to go http.Server's source code), .

> 
> I think that the problem can be caused by the fact that we use the default `MaxIdleConnsPerHost` in the client settings, which limits the number of idle connections to 2 on the client site:
> 
> https://github.com/pyroscope-io/client/blob/72c28da1c0a344149dcee1264a9f3f7bc9a78ee2/upstream/remote/remote.go#L52-L86
> 
> `MaxConnsPerHost` limits the total number of connections per host, including connections in the active, and idle states.
> 
> However, it's not entirely clear for me why exactly the server initiated the connection termination (sending FIN, ACK) and not the client. It would be nice to look at the [flow graph](https://www.wireshark.org/docs/wsug_html_chunked/ChStatFlowGraph.html). And it does not explain the EOF error, as well: the client would establish a new connection.
> 
> In turn, I'd suggest to try setting `MaxConnsPerHost` == `MaxIdleConnsPerHost` == `MaxIdleConns` == `number of threads (hardcoded to 4)` before digging into debugging, as this seems to be the most obvious fix.
> 
> @ray2011, what do you think?

![image](https://user-images.githubusercontent.com/7893714/182718207-d9118f68-011a-4949-9240-e1286f2db5c6.png)
The number of threads is 4 already.

Change the MaxConnsPerHost to 1 is workable, because it can make the conn that established but not send first request in 10s disapper. But it  would affect the efficiency.

**Comment by ray2011** [comment]
> Also, I'm thinking about increasing the default timeouts on the server side: with TLS transport, Go http server sets deadlines right after [accepting the connection](https://github.com/golang/go/blob/29b9a328d268d53833d2cc063d1d8b4bf6852675/src/net/http/server.go#L1867-L1872):
> 
> ```go
> tlsTO := c.server.tlsHandshakeTimeout()
> if tlsTO > 0 {
> 	dl := time.Now().Add(tlsTO)
> 	c.rwc.SetReadDeadline(dl)
> 	c.rwc.SetWriteDeadline(dl)
> }
> ```
> 
> (`tlsHandshakeTimeout` picks smallest value from `ReadTimeout`, `ReadHeaderTimeout`, and `WriteTimeout`).
> 
> While in other cases it sets the deadline [after the body is read](https://github.com/golang/go/blob/3ba31558d1bca8ae6d2f03209b4cae55381175b3/src/net/http/server.go#L744-L756). More about it here: [So you want to expose Go on the Internet](https://blog.cloudflare.com/exposing-go-on-the-internet/#timeouts).
> 
> I would set the following settings by default:
> 
> ```go
> ReadTimeout: 30 * time.Second,
> WriteTimeout: 30 * time.Second,
> IdleTimeout: 90 * time.Second,
> ```
> 
> And, if TLS is configured, set all those to 90 seconds.
> 
> /cc @petethepig

This is very good. I suggest not set server timeout as the mutliple of 10s(the client update rate),  try use 33s perhaps better.   It make "server close idle conn" and "client upload" cant happen at the same time

**Comment by veloting** [comment]
> > Also, I'm thinking about increasing the default timeouts on the server side: with TLS transport, the Go HTTP server sets deadlines right after [accepting the connection](https://github.com/golang/go/blob/29b9a328d268d53833d2cc063d1d8b4bf6852675/src/net/http/server.go#L1867-L1872):
> > ```go
> > tlsTO := c.server.tlsHandshakeTimeout()
> > if tlsTO > 0 {
> > 	dl := time.Now().Add(tlsTO)
> > 	c.rwc.SetReadDeadline(dl)
> > 	c.rwc.SetWriteDeadline(dl)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (`tlsHandshakeTimeout` picks smallest value from `ReadTimeout`, `ReadHeaderTimeout`, and `WriteTimeout`).
> > While in other cases it sets the deadline [after the body is read](https://github.com/golang/go/blob/3ba31558d1bca8ae6d2f03209b4cae55381175b3/src/net/http/server.go#L744-L756). More about it here: [So you want to expose Go on the Internet](https://blog.cloudflare.com/exposing-go-on-the-internet/#timeouts).
> > I would set the following settings by default:
> > ```go
> > ReadTimeout: 30 * time.Second,
> > WriteTimeout: 30 * time.Second,
> > IdleTimeout: 90 * time.Second,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And, if TLS is configured, set all those to 90 seconds.
> > /cc @petethepig
> 
> This is very good. I suggest not setting server timeout as the multiple of 10s(the client update rate), try to use 33s perhaps better. It makes "server close idle conn" and "client upload" cant happen at the same time

good idea

**Comment by ray2011** [comment]
any update?

**Comment by ray2011** [comment]
UploadRate can be configed now.
