### ISSUE TITLE
Create tags for pinning in code

### ISSUE THREAD

**Issue by prabhatsharma** [pyroscope-io/client#3]
Creating a tag would be great for pinning in the utilizing codebase.

**Comment by petethepig** [comment]
@prabhatsharma Great point, thanks for the feedback!

**Comment by kavu** [comment]
Hey guys! Any progress on that one? Thanks!

**Comment by petethepig** [comment]
Sorry about the delay. Just tagged our first two releases (https://github.com/pyroscope-io/client/tags)

@kavu Love your go_reuseport library by the way. Used it a ton at the previous job :)

**Comment by kavu** [comment]
@kavu Thanks, glad you found it useful!
