### ISSUE TITLE
types should not be internal

### ISSUE THREAD

**Issue by smallnest** [pyroscope-io/client#4]
![image](https://user-images.githubusercontent.com/865763/151140917-57aab7dc-fadf-4295-90ed-ac8502823f30.png)

Just like the above, types should not be internal, otherwise users can't customize their ProfileTypes.

**Comment by kolesnikovae** [comment]
Oh, we overlooked that. Thank you @smallnest for reporting the issue! Will be fixed ASAP.

**Comment by kavu** [comment]
Glad this issue exists! Tried to integrate the client, but can't even setup the profile types :)
