### ISSUE TITLE
Add support for mutex, block, and gouroute profiles

### ISSUE THREAD

**Issue by kolesnikovae** [pyroscope-io/client#6]
To be in sync with pull mode, we need to extend the push client. See https://github.com/pyroscope-io/pyroscope/issues/775

**Comment by akarmarkar** [comment]
@kolesnikovae It would be wonderful to have this feature. I made local changes to the go client to upload the goroutine/mutex/block profiles. From the logs, it looks like they are uploaded without issues, but I am unable to see anything in the UI. Are UI side changes needed for this feature ?

**Comment by kolesnikovae** [comment]
Hey @akarmarkar! That's awesome! Pyroscope server handles pprof data according to the configuration: https://github.com/pyroscope-io/pyroscope/blob/28652bb46aa98d046d352bcd828972f8595f1a02/pkg/storage/tree/pprof.go#L15-L37 - I think it should be enough to update it according to https://github.com/pyroscope-io/pyroscope/issues/768#issuecomment-1023419863. After that profiling data should be available in UI but some parts (units, description, etc) may be incorrect. If you open a PR I think I can quickly modify the server, test the client side and see what else we need to do.

**Comment by petethepig** [comment]
This is already implemented.
