### ISSUE TITLE
Failed to push profiler to server because of 403 Forbidden  

### ISSUE THREAD

**Issue by koolay** [pyroscope-io/client#7]
Agent:

```go
	pyroscope.Start(pyroscope.Config{
		ApplicationName: "debug-v2",
		// replace this with the address of pyroscope server
		ServerAddress: "http://localhost:4040",

		// you can disable logging by setting this to nil
		Logger:    pyroscope.StandardLogger,
		AuthToken: "psx-xx-xx-xx",
	})

```
Server config:

```yaml
# /tmp/config.yaml
auth:
  ingestion:
    enabled: true
  internal:
    admin:
      create: true
    enabled: true
    signup-enabled: true
```
<img width="708" alt="image" src="https://user-images.githubusercontent.com/4273490/156979834-510f79ec-0b5e-49b7-b081-6ea98f791afd.png">

Log:

```
[DEBUG] profiling session reset 2022-03-07 14:26:10 +0800 CST
[DEBUG] uploading at http://localhost:4040/ingest?aggregationType=sum&from=1646634370&name=debug-dataview-v2%7B%7D&sampleRate=100&spyName=gospy&units=samples&until=1646634380
[DEBUG] content type: multipart/form-data; boundary=eda11cede7e28da1c78335cc835cdade3282a4a7c9abeeae855e9ff84d32
[ERROR] upload profile: failed to upload a profile
```

And the failure is `403 Forbidden`

**Comment by koolay** [comment]
https://github.com/pyroscope-io/pyroscope/blob/5801024a2f8dd46ae130ff1844652089ff55edd3/pkg/server/controller.go#L209

 As the code, ingestion token needs `AdminRole` and `AgentRole` not `AdminRole` or `AgentRole`.

**Comment by kolesnikovae** [comment]
Thank you for reporting the issue @koolay! This is a bug, the fix will be released shortly: https://github.com/pyroscope-io/pyroscope/pull/923.

**Comment by koolay** [comment]
@kolesnikovae  Thanks for your fix so quickly! Could you please make a new release image?
